users = require("users")
packages = require("packages")
cron = require("cron")
misc = require("misc")

users.check_users()
misc.check_harmful_files()
packages.check_packages()
cron.check_cron()
misc.check_firewall()
misc.check_syn_cookies()
